import type { Metadata } from "next";
import localFont from "next/font/local";
import {Nunito} from "next/font/google";
import "./globals.css";
import Header from "./(Global)/Header";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const nunito = Nunito({subsets:["latin"]});

export const metadata: Metadata = {
    title: "NextGen marketing agency",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.className} antialiased`}
            >
                <Header />
                <div className="max-w-7xl mx-auto px-3 py-5">{children}</div>
            </body>
        </html>
    );
}
